Magnet/Magnet/models.py
# -*- coding: utf-8 -*-
import datetime

from flask_login import UserMixin, login_manager
from werkzeug.security import generate_password_hash, check_password_hash

from Magnet.Magnet import db


class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column('user_id', db.Integer, primary_key=True, autoincrement=True)
    email = db.Column('email', db.String(200), index=True, unique=True)
    password_hash = db.Column('password_hash', db.String(200))
    registered_on = db.Column('registered_on', db.DateTime, default=datetime.datetime.now)
    accept_conditions = db.Column('accept_conditions', db.Boolean, default=False)
    confirmed = db.Column('confirmed', db.Boolean, default=False)
    confirmed_on = db.Column('confirmed_on', db.DateTime, nullable=True)
    admin = db.Column('admin', db.Boolean, default=False)
    permissions = db.Column('permissions', db.Integer, default='4')
    authorized = db.Column('authorized', db.Boolean, default=True)
    name = db.Column('name', db.String(100), nullable=True)
    company = db.Column('company', db.String(100), nullable=True)
    bio = db.Column('bio', db.String(600), nullable=True)

    def __repr__(self):
        return '<User {}>'.format(self.email)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Cafam(UserMixin, db.Model):
    __tablename__ = "cafam"
    id = db.Column('user_id', db.Integer, primary_key=True, autoincrement=True)
    email = db.Column('email', db.String(200), index=True, unique=True)
    city = db.Column('city', db.String(500), index=True)
    level = db.Column('level', db.String(500), index=True)
    position = db.Column('position', db.String(500), index=True)

Magnet/Magnet/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask, render_template
from flask_restful import reqparse, abort, Api, Resource
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy


# Define the WSGI application object
app = Flask(__name__)
cors = CORS(app, resources={r"*": {"origins": "*"}})
api = Api(app)

# Define the database object which is imported by modules and controllers
db = SQLAlchemy(app)

# Configurations
app.config.from_object('config')


# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('errors/404.html'), 404


# Import a module / component using its blueprint handler variable (mod_auth)
from Magnet.mod_start.views import module_start as start_module


# Register blueprint(s)
app.register_blueprint(start_module)


# Build the database
db.create_all()

Magnet/Magnet/mod_start/views.py
# -*- coding: utf-8 -*-
# Standard library imports
import os
import glob

# Third party imports
from flask import Flask, g, Blueprint, render_template, flash, session, redirect, url_for, request, send_from_directory, \
    send_file, jsonify
from bokeh.core.properties import value
from bokeh.models import (HoverTool, FactorRange, Plot, LinearAxis, Grid, Range1d)
from bokeh.models.glyphs import VBar
from bokeh.plotting import Figure, show, output_file
from bokeh.embed import components
from bokeh.models.sources import ColumnDataSource
import numpy as np
import pandas as pd

# Local application imports
import Magnet.analytics.extractores.claro_mobile_paquetes as claro_paquetes
import Magnet.analytics.extractores.movistar_mobile_paquetes as movistar_paquetes
import Magnet.analytics.extractores.tigoune_mobile_paquetes as tigo_paquetes

import Magnet.analytics.extractores.claro_mobile_pospago as claro_pospago
import Magnet.analytics.extractores.movistar_mobile_pospago as movistar_pospago

import Magnet.analytics.extractores.tigoune_cellphones as tigo_celulares

# Define the blueprint: 'start', set its url prefix: app.url/start
module_start = Blueprint('start', __name__, url_prefix='/')


''' Definiciones de START'''


@module_start.route('/', methods=['GET'])
def index():
    table = claro_paquetes.get_plans()
    return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes Claro")


@module_start.route('/paquetes_claro', methods=['GET'])
def paquetes_claro():
    table = claro_paquetes.get_plans()
    return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes Claro")


@module_start.route('/paquetes_movistar', methods=['GET'])
def paquetes_movistar():
    table = movistar_paquetes.get_plans()
    return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes Movistar")


@module_start.route('/paquetes_tigo', methods=['GET'])
def paquetes_tigo():
    table = tigo_paquetes.get_plans()
    return render_template('dashboard/paquetes.html', table=table, section_title="Paquetes TIGOUNE")


@module_start.route('/pospago_claro', methods=['GET'])
def pospago_claro():
    table = claro_pospago.get_plans()
    return render_template('dashboard/pospago.html', table=table, section_title="Pospago Claro")


@module_start.route('/pospago_movistar', methods=['GET'])
def pospago_movistar():
    table = movistar_pospago.get_plans()
    return render_template('dashboard/pospago.html', table=table, section_title="Pospago Movistar")


@module_start.route('/celulares_tigo', methods=['GET'])
def celulares_tigo():
    table = tigo_celulares.get_cellphones()
    return render_template('dashboard/celulares.html', table=table, section_title="Celulares TIGOUNE")


@module_start.route('/download_data/<file>', methods=['GET'])
def download_data(file):
    try:
        data_directory = os.path.abspath(os.path.join(__file__, "../../../Magnet/analytics/data"))
        file_path = glob.glob(data_directory + '/**/' + '{}.csv'.format(file), recursive=True)
        return send_file(file_path[0], attachment_filename="{}.csv".format(file), as_attachment=True)
    except Exception as e:
        return str(e)


@module_start.route('/data/api/v1.0/<tipo>/<operador>', methods=['GET'])
def get_data(tipo, operador):
    if tipo == "planes" and operador == "claro":
        list = claro_pospago.get_plans()
        return jsonify(results=list)
    elif tipo == "planes" and operador == "movistar":
        list = movistar_pospago.get_plans()
        return jsonify(results=list)
    elif tipo == "paquetes" and operador == "claro":
        list = claro_paquetes.get_plans()
        return jsonify(results=list)
    elif tipo == "paquetes" and operador == "movistar":
        list = movistar_paquetes.get_plans()
        return jsonify(results=list)
    elif tipo == "paquetes" and operador == "tigo":
        list = tigo_paquetes.get_plans()
        return jsonify(results=list)
    elif tipo == "celulares" and operador == "tigo":
        list = tigo_celulares.get_cellphones()
        return jsonify(results=list)
    else:
        return jsonify(results="Sin Resultados")


@module_start.route('/dashboard', methods=['GET'])
def get_dashboard():
    # p = Figure(title='Sine', x_axis_type="datetime", plot_width=1110, plot_height=400)
    # x = np.linspace(-10, 10, 200)
    # y = np.sin(x)
    # p.line(x=x, y=y)
    # script, div = components(p)

    operadores = ['Claro', 'Movistar', 'Tigo-Une']
    categorias = ["Voz", "Datos", "Voz y Datos"]
    colors = ["#c9d9d3", "#718dbf", "#e84d60"]

    data = {'operadores': operadores,
            'Voz': [2, 1, 4],
            'Datos': [5, 3, 4],
            'Voz y Datos': [3, 2, 4]}

    p = Figure(x_range=operadores, plot_width=1400, plot_height=250, title="Tipos de Planes x Operador",
               toolbar_location=None, tools="hover", tooltips="$name @operadores: @$name")

    p.vbar_stack(categorias, x='operadores', width=0.9, color=colors, source=data,
                 legend=[value(x) for x in categorias])

    script, div = components(p)

    return render_template('dashboard/dashboard.html', script=script, div=div, section_title="Dashboard")

Magnet/Magnet/templates/core/layout.html
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Planes y Tarifas - POST[data]</title>
    {% endif %}
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicons
    ================================================== -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}" type="image/x-icon">
    <link rel="apple-touch-icon" href="../static/img/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../static/img/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../static/img/apple-touch-icon-114x114.png">

    <!-- Bootstrap
    ================================================== -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- Fonts
    ================================================== -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
          integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <!-- Custom Stylesheets
    ================================================== -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/one-page-wonder.min.css') }}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <![endif]-->

    <style> html { scroll-behavior: smooth; } </style>

</head>

<body>
{% include "core/navbar.html" %}
{% block plans %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/js/bootstrap.bundle.js"></script>
</html>

Magnet/Magnet/templates/core/navbar.html
{% block navbar %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="">
            <img src="{{ url_for('static', filename='img/logoweb_small.png') }}" width="" height="60" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="nav navbar-nav ml-auto">
                <ul class="nav navbar-nav ml-auto">
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Celulares
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Operadores</b></span>
                                <a class="dropdown-item" href="{{ url_for('start.celulares_tigo') }}">Celulares Tigo</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Planes POSTPAGO
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Operadores</b></span>
                                <a class="dropdown-item" href="{{ url_for('start.pospago_claro') }}">Planes Claro</a>
                                <a class="dropdown-item" href="{{ url_for('start.pospago_movistar') }}">Planes
                                    Movistar</a>
                                <a class="dropdown-item" href="#">Planes TIGO</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu3"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Paquetes PREPAGO
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Operadores</b></span>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_claro') }}">Paquetes Claro</a>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_movistar') }}">Paquetes
                                    Movistar</a>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_tigo') }}">Paquetes TIGO</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu4"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                Dashboard
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Categorias</b></span>
                                <a class="dropdown-item" href="{{ url_for('start.get_dashboard') }}">Planes x Operador</a>
                            </div>
                        </div>
                    </li>
                                        <li>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu5"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="
                                        border-right-width: 1px; margin-right: 25px;">
                                API
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <span class="dropdown-item-text"><b>Operadores</b></span>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_claro') }}">API Planes</a>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_movistar') }}">API Paquetes</a>
                                <a class="dropdown-item" href="{{ url_for('start.paquetes_tigo') }}">API Celulares</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

Magnet/Magnet/templates/dashboard/celulares.html
{% extends "core/layout.html" %}

{% block plans %}
<style>
table {
  width:100%;
}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
  text-align: left;
}
table#t01 tr:nth-child(even) {
  background-color: #eee;
}
table#t01 tr:nth-child(odd) {
 background-color: #fff;
}
table#t01 th {
  background-color: black;
  color: white;
}
table#t01 th {
  background-color: black;
  color: white;
}
.table-condensed{
  font-size: 14px;
}

</style>
<section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align: center">
        <h1>{{ section_title }}</h1>
    </div>
    <br>
    <div class="container">
        <table class="table table-sm table-condensed" style="width:80%; margin-left: 10%;">
            <thead class="thead-dark">
            <tr>
                <th style="width:100px;">Fecha</th>
                <th>Nombre</th>
                <th>Precio</th>
            </tr>
            </thead>
            <tbody>
            {% for row in table %}
            <tr>
                <td>{{row[0]}}</td>
                <td>{{row[1]}}</td>
                <td>{{row[2]}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</section>
<section>
    <div class="container">
        <a href="{{ url_for('start.download_data', file='claro_tarifas_paquetes') }}" class="btn btn-primary btn-xl rounded-pill mt-5" style="margin-left: 40%;">Descargar Información</a>
    </div>
    <br>
    <br>
</section>
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
{% endblock %}

Magnet/Magnet/templates/dashboard/dashboard.html
{% extends "core/layout.html" %}

{% block plans %}
<style>
table {
  width:100%;
}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
  text-align: left;
}
table#t01 tr:nth-child(even) {
  background-color: #eee;
}
table#t01 tr:nth-child(odd) {
 background-color: #fff;
}
table#t01 th {
  background-color: black;
  color: white;
}
.table-condensed{
  font-size: 14px;
}

</style>
<section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align: center">
        <h1>{{ section_title }}</h1>
    </div>
    <br>
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.css" rel="stylesheet">
    <link href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.css" rel="stylesheet">
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js"></script>
    <script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.js"></script>
    <br>
    <br>
    <div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Planes Operador</h3>
            </div>
            <div class="card-body">
                {{ script | safe }}
                {{ div | safe }}
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
{% endblock %}

Magnet/Magnet/templates/dashboard/paquetes.html
{% extends "core/layout.html" %}

{% block plans %}
<style>
table {
  width:100%;
}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
  text-align: left;
}
table#t01 tr:nth-child(even) {
  background-color: #eee;
}
table#t01 tr:nth-child(odd) {
 background-color: #fff;
}
table#t01 th {
  background-color: black;
  color: white;
}
.table-condensed{
  font-size: 14px;
}
</style>
<section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align: center">
        <h1>{{ section_title }}</h1>
    </div>
    <br>
    <div class="container">
        <table class="table table-sm table-condensed" style="width:90%; margin-left: 5%;">
            <thead class="thead-dark">
            <tr>
                <th style="width:100px;">Fecha</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Datos</th>
                <th>Minutos</th>
                <th>SMS</th>
                <th>Zero Rating</th>
                <th>Apps</th>
                <th>Vigencia</th>
            </tr>
            </thead>
            <tbody>
            {% for row in table %}
            <tr>
                <td>{{row[0]}}</td>
                <td>{{row[1]}}</td>
                <td>{{row[2]}}</td>
                <td>{{row[3]}}</td>
                <td>{{row[4]}}</td>
                <td>{{row[5]}}</td>
                <td>{{row[6]}}</td>
                <td>{{row[7]}}</td>
                <td>{{row[8]}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</section>
<section>
    <div class="container">
        <a href="{{ url_for('start.download_data', file='claro_tarifas_paquetes') }}" class="btn btn-primary btn-xl rounded-pill mt-5" style="margin-left: 40%;">Descargar Información</a>
    </div>
    <br>
    <br>
</section>
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
{% endblock %}

Magnet/Magnet/templates/dashboard/pospago.html
{% extends "core/layout.html" %}

{% block plans %}
<style>
table {
  width:100%;
}
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
  text-align: left;
}
table#t01 tr:nth-child(even) {
  background-color: #eee;
}
table#t01 tr:nth-child(odd) {
 background-color: #fff;
}
table#t01 th {
  background-color: black;
  color: white;
}
.table-condensed{
  font-size: 14px;
}
</style>
<section>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align: center">
        <h1>{{ section_title }}</h1>
    </div>
    <br>
    <div class="table table-sm table-condensed" class="container">
        <table style="width:80%; margin-left: 10%;">
            <thead class="thead-dark">
            <tr>
                <th style="width:100px;">Fecha</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Datos</th>
                <th>Minutos</th>
                <th>SMS</th>
                <th>Zero Rating</th>
                <th>Apps</th>
            </tr>
            </thead>
            <tbody>
            {% for row in table %}
            <tr>
                <td>{{row[0]}}</td>
                <td>{{row[1]}}</td>
                <td>{{row[2]}}</td>
                <td>{{row[3]}}</td>
                <td>{{row[4]}}</td>
                <td>{{row[5]}}</td>
                <td>{{row[6]}}</td>
                <td>{{row[7]}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</section>
<section>
    <div class="container">
        <a href="{{ url_for('start.download_data', file='claro_tarifas_paquetes') }}" class="btn btn-primary btn-xl rounded-pill mt-5" style="margin-left: 40%;">Descargar Información</a>
    </div>
    <br>
    <br>
</section>
{% endblock %}

{% block footer %}
<!-- Footer -->
<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2018</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
{% endblock %}